apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31000   # Specify the nodePort you desire, make sure it's within the range 30000-32767
  selector:
    app: backend

